"""empty message

Revision ID: 17a8193bf51e
Revises: e25edaf9197e
Create Date: 2023-12-01 21:43:16.388421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a8193bf51e'
down_revision: Union[str, None] = 'e25edaf9197e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foo', sa.Column('desc1', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foo', 'desc1')
    # ### end Alembic commands ###
